[package]
name = "mdmp3tomp4"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serial_test = "2.0"
id3 = "1"         # for reading ID3 APIC cover art
glob = "0.3"
